---
title: "twitter-example"
output: html_document
date: "2022-09-13"
---
For R API, I used twitter to scratch keywords like "instagram, tiktok, youtube, facebook" to scratch users' attitudes about these platforms. 
```{r}
library(selectr)
library(rvest)
library(xml2)
library(rtweet) # for scraping tweets
library(wordcloud2) # for generating really cool looking wordclouds
library(tm) # for text minning
library(dplyr) # loads of fun stuff including piping
library(ROAuth)
library(jsonlite)
library(httpuv)
```
set API parameters
```{r}
consumer_key = "9TVmMW3pyds9CwlMhgXBK5Bu5"
consumer_secret = "lTXYO7I5nKTGOp7zJG7jtf7dCmYoQLtbgB4a0w6BZN6ct4mNxT"
access_token = "1553871190036516864-ahw9mcZ1pq36DzwsD7CFgvU0iMnOy4"
access_token_secret = "8DhWYScYuF6KofqS9Gt7ajYs7B4DZKkZSBhoMPgyfnTFp"
bearer_token = "AAAAAAAAAAAAAAAAAAAAAOfFfQEAAAAARkEQiS1bfu9c96%2FD%2FvzbetKGYZk%3DKNBdl2kUeIysZ9wV6n6O4X3zp5enoR6Onp6LqEKQVldRKaDcum"

```

```{r}
library(twitteR)
requestURL='https://api.twitter.com/oauth/request_token'
accessURL='https://api.twitter.com/oauth/access_token'
authURL='https://api.twitter.com/oauth/authorize'

s_key  = 'instagram OR tik tok OR facebook OR youtube'
n_tweets = 250 

twitteR:::setup_twitter_oauth(consumer_key, consumer_secret,access_token,access_token_secret)
Search1<-twitteR::searchTwitter(s_key,n=n_tweets, since="2022-04-01",lang="en")
```

```{r}
TweetsDF<- twListToDF(Search1)
TweetsDF
```
Place tweets in a new file
```{r}
FName = "~/Desktop/wemediaexample.txt"
MyFile <- file(FName)
cat(unlist(TweetsDF), " ", file=MyFile, sep="\n")
close(MyFile)
```

```{r}
library("tm")
library("SnowballC")
library("wordcloud")
library("RColorBrewer")
```
```{r}
twittertext = Corpus(VectorSource(TweetsDF$text))
toSpace = content_transformer(
              function (x, pattern)
              gsub(pattern, " ", x))
twittertext1 = tm_map(twittertext, toSpace, "/")
twittertext1 = tm_map(twittertext, toSpace, "@")
twittertext1 = tm_map(twittertext, toSpace, "#")
strwrap(twittertext1)
```
```{r}
twittertext1 = tm_map(twittertext1, content_transformer(tolower))
twittertext1 = tm_map(twittertext1, removeNumbers)
twittertext1 = tm_map(twittertext1, stripWhitespace)
```

```{r}
twittertm = TermDocumentMatrix(twittertext1)
m = as.matrix(twittertm)
v = sort(rowSums(m), 
         decreasing = TRUE)
d = data.frame(word = names(v),
               freq = v)
head(d, 10)
```
```{r}
wordcloud(words = d$word, 
          freq = d$freq,
          min.freq = 1, 
          max.words = 200,
          random.order = FALSE, 
          rot.per = 0.35, 
          colors = brewer.pal(8, "Dark2"))
```

